### ISSUE TITLE
Empty device list

### ISSUE THREAD

**Issue by enloja** [reincubate/ricloud-js#6]
2FA has been enabled, choose a trusted device [1/0] :1
Selected: Challenge all 2FA devices

A code has been sent to your device. Please enter code: 939158
login result: { key: '414c5a2f-f65a-472d-ab7f-258403968271', devices: {} }
authToken: undefined

AssertionError [ERR_ASSERTION]: device is a required argument

**Comment by afit** [comment]
Hey @enloja, thanks for the ticket. Our Python API client has a fix for this: you can see it [here](https://github.com/reincubate/ricloud).

**Comment by hlynursmari1** [comment]
Closing prior to repo archival.
